### ISSUE TITLE
Paideia MVP - DONOTUSE

### ISSUE THREAD

**Issue by vikingphoenix** [ergo-pad/ergopad-api#103]
# Pages
- [ ] [Dashboard](https://www.paideia.im/dao)
- [ ] [Proposals/All](https://www.paideia.im/dao/proposals/all)
- [ ] [Proposals/Following](https://www.paideia.im/dao/proposals/following)
- [ ] [Proposals/Mine](https://www.paideia.im/dao/proposals/mine)
- [ ] [Proposals/Past](https://www.paideia.im/dao/proposals/past)
- [ ] [Members](https://www.paideia.im/dao/members)
- [ ] [Activity](https://www.paideia.im/dao/activity)
- [ ] [Settings/Edit Profile](https://www.paideia.im/dao/profile/edit)
- [ ] [Settings/Notifications](https://www.paideia.im/dao/notifications/edit)
- [ ] [Settings/Wallet](https://www.paideia.im/dao/wallet)
- [ ] [DAO Config](https://www.paideia.im/dao/dao-config)
- [ ] [Education](https://www.paideia.im/education)
- [ ] [About](https://www.paideia.im/about)
- [ ] [404](https://www.paideia.im/404)
- [ ] [Creation](https://www.paideia.im/creation) ??
- [ ] [Projects](https://www.paideia.im/projects) ??

# Features
- [ ] [Connect Wallet](https://www.paideia.im/dao/wallet)
- [ ] [Notifications Bell](https://www.paideia.im/dao)
- [ ] [DAO Selector](https://www.paideia.im/dao)
- [ ] [Discussion Page](https://www.paideia.im/dao/discussion/1) - View and Create
- [ ] [Activity Log](https://www.paideia.im/dao/activity)
- [ ] [Create New...](https://www.paideia.im/dao/create)
- [ ] [Create New Proposal](https://www.paideia.im/dao/proposal/create)
- [ ] [Create New Discussion](https://www.paideia.im/dao/discussion/create)
- [ ] [Banner Message](https://www.paideia.im/dao)
- [ ] [Terminate DAO](https://www.paideia.im/dao/dao-config/terminate)

# Misc
- [ ] Distribution page (currently 2 versions: /distribution and /distributions)
> /distribution/redeem..
> /distribution/[id]..
> /distributions/create..
- Financials section: token, treasury, recurring, rokenomics, treasury
- Staking: manage
# Notes
- Borrow from existing ErgoPad API
- AppKit
- Routes for frontend/application interface
- Architect solution for onchain DAO existance (to allow to work 100% defi)
- Member page

Will interact with UI requests (see wireframe): https://www.figma.com/file/mU9Y1RCCHOSO3P0AjulhFl/Wireframes?node-id=25%3A589

The DAO information will need to be stored on-chain.  This will require an information schema that is able to identify DAO's created (i.e. linked to unique tx/wallet).
- [ ] divide the elements of the DAO itself (i.e. tokens, wallets, organizational structure) and the UI and Paideia services
- [ ] Paideia UX services will be a web2 service, backended by a traditional database
- [ ] DAO configuration created by paideia will exist entirely on-chain
