### ISSUE TITLE
NFT Sale Infrastructure

### ISSUE THREAD

**Issue by vikingphoenix** [ergo-pad/ergopad-api#407]
## Timeline:
- December 2022
- May need web2 solution to speed things up, so decouple minting contracts to work on their own

## Tasks:
- [ ] Simplify design documentation (from Luca)
- [ ] Implement minting contract (prior to sales contract); need brainstorming session on this

Components:
- [ ] M.O.R.E. Frontend
- [ ] RNG oracle (waiting for 2.0)
- [ ] API 
- [ ] Smart Contracts - needs testing

## Frontend 
noob to setup basic site with common design

## API
- noob/leif to setup API to automate SC from frontend
- using native scala for this (https://github.com/noob77777/more-scala-sdk)

**Comment by noob77777** [comment]
Need to break this task into smaller subtasks
