### ISSUE TITLE
Add foreign-key constraints to paideia db

### ISSUE THREAD

**Issue by noob77777** [ergo-pad/ergopad-api#426]
### Subtasks
- [x] add constraints for user tables
- [x] add constraints for dao schemas
- [x] add constraints for proposals
- [x] testing: Make sure all inserts and deletes work as expected

### Changes
- https://github.com/ergo-pad/paideia-data/commit/ad5cb259632dd212b1012d92bfa8002a7061cd55
- https://github.com/ergo-pad/paideia-data/commit/4e4d1fc0a2b4595d1899730f341cb3be550bbbf2
- https://github.com/ergo-pad/paideia-data/commit/6a49e64196ae6da7700542cec32928b70a5dca45
- https://github.com/ergo-pad/paideia-data/commit/07c043cd301ef1dccd6344784280293540b15777
