### ISSUE TITLE
Paideia API: CMS

### ISSUE THREAD

**Issue by noob77777** [ergo-pad/ergopad-api#511]
## CMS for Paideia
check out blog/[id] for a sample page
MarkdownRender.tsx in /lib/ should cover most things you need already

CMS: 
- Add/edit/remove blog pages
- Choose what blog pages are displayed in Education -> Learn section 
- Add/edit/remove featured projects (with blurb)
- Add/edit/remove quotes for user feedback section (up to 3 quotes)
- Add/edit/remove FAQ questions

### Tasks
- [x] Blogs API
- [x] Quotes API
- [x] FAQ API
- [x] Blogs Frontend Integration
- [x] Highlights Frontend Integration
- [x] Education Frontend Integration
- [x] FAQ Frontend Integration
- [x] Quotes Frontend Integration

### Content
- [x] Use swagger/api to populate data

**Comment by esot321c** [comment]
Tested using swagger API to post and edit a blog post. Works great. 

The only issue is the navbar of a blog post. I think we need to add links to headers and give the header a class.
