### ISSUE TITLE
Wrapping up Loose Ends before Paideia

### ISSUE THREAD

**Issue by vikingphoenix** [ergo-pad/ergopad-api#69]
- [ ] parameterize sql
- [ ] security audit (nmap, etc..)
- [ ] optimization (at least identify opportunities)
- [ ] organize config/secrets
 .. move const to config
 .. docker (from config) vs dotenv (loaded at app runtime)
